### ISSUE TITLE
Tone down re-exports and glob imports

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#1803]
We have about four different "preludes" in `util`, some of which reference each other. 
`use util::*` is very opaque and gives almost no hint as to what is actually being imported -- stuff from util, std, and other crates is all jumbled together.
- [x] common module in ethcore
- [x] remove `std` re-exports from util
- [ ] rest of util? not sure how to break it down.

**Comment by NikVolf** [comment]
agreed, i had hard time when refactoring because of this glob imports

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still realistic to implement. If so, please add an assignee and a milestone, or close otherwise.

**Comment by debris** [comment]
most of the re-exports and all glob imports has been removed from util
