### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by debris** [paritytech/parity#184]
- [x] - ubuntu build #277
- [x] - osx build #194
- [x] - build every PR #194
- [x] - update the docs (use something like [this](https://github.com/defyrlt/lithium/blob/master/.travis.yml)) #311
- [x] - run coverage tests #277
