### ISSUE TITLE
Metropolis release

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#4833]
- [x] [EIP-208 (86): Account abstraction](https://github.com/ethereum/EIPs/pull/208) | #4697 
- [x] [EIP-98: Receipt state root removal](https://github.com/ethereum/EIPs/issues/98) |  #4296 
- [x] [EIP-210 (96): Blockhash and state root changes](https://github.com/ethereum/EIPs/pull/210) | #5505 
- [x] [EIP-100: Change difficulty adjustment to target mean block time including uncles](https://github.com/ethereum/EIPs/issues/100) | #5027 
- [x] [EIP-198 (101): Precompile for bigint modular exponentiation](https://github.com/ethereum/EIPs/pull/198) | #4926 
- [x] [EIP-206 (140): REVERT opcode](https://github.com/ethereum/EIPs/pull/206) | #5477 
- [x] [EIP-214 (116): STATIC_CALL opcode](https://github.com/ethereum/EIPs/pull/214) | #4851
- [x] [EIP-211 (5/8) RETURNDATACOPY and RETURNDATASIZE](https://github.com/ethereum/EIPs/pull/211) | #5678
- [x] [EIP-212 Precompiled contract for pairing check](https://github.com/ethereum/EIPs/pull/212) | #5307 
- [x] [EIP-213 Precompiled contracts for addition and scalar multiplication on the elliptic curve alt_bn128](https://github.com/ethereum/EIPs/pull/213) | https://github.com/paritytech/parity/pull/4999
- [x] [EIP-649 Difficulty bomb delay and issuance reduction](https://github.com/ethereum/EIPs/pull/669) | #5855
- [x] [EIP-658 Embedding transaction return data in receipts](https://github.com/ethereum/EIPs/pull/658) | #5855

--- 

For reference - Byzantium Meta: [EIP-609](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-609.md)

**Comment by debris** [comment]
I will take  `EIP-116: STATIC_CALL opcode`

**Comment by rphmeier** [comment]
I'll take `EIP-198 (101): Precompile for bigint modular exponentiation`

**Comment by NikVolf** [comment]
Will take EIP-213 Precompiled contracts for addition and scalar multiplication on the elliptic curve alt_bn128

**Comment by debris** [comment]
I will take 

`EIP-100: Change difficulty adjustment to target mean block time including uncles`
`EIP-206 (140): REVERT opcode`

**Comment by rphmeier** [comment]
@NikVolf The gas costs for those haven't been sorted yet, unfortunately.

**Comment by NikVolf** [comment]
@rphmeier yep but we need to sort the math meanwhile anyway

**Comment by rphmeier** [comment]
I can take `EIP-210 (96): Blockhash and state root changes` also

**Comment by tomusdrw** [comment]
Just realized we also need to update transaction queue propagation/miners strategy for EIP-208 (EIP-86)

**Comment by rphmeier** [comment]
@tomusdrw yeah, it should be done with a whitelist of accepted abstraction contracts. Running to check if it pays the miner is a DoS vulnerability.

I think we can do it similarly to the service-transaction checker: either pass a list of addresses from the command line or fetch them from a Parity-maintained contract.

**Comment by arielgabizon** [comment]
@NikVolf  has the elliptic curve stuff been added? We need it for something we're doing at the cornell bootcamp

**Comment by debris** [comment]
@arielgabizon yes it has in #4999. You can activate it on your chain by modifying `activate_at` variable in [spec file](https://github.com/paritytech/parity/pull/4999/files#diff-09e1141f3610b5496b23dd6fa862d325R194)

**Comment by 5chdn** [comment]
FYI "EIP649" via https://github.com/ethereum/EIPs/pull/669 implements https://github.com/ethereum/EIPs/issues/649 and supersedes https://github.com/ethereum/EIPs/issues/186 was recently accepted in https://github.com/ethereum/pm/issues/20 via https://github.com/ethereum/EIPs/pull/688

**Comment by 5chdn** [comment]
Added [EIP-658](https://github.com/ethereum/EIPs/pull/658) and also requires split into two forks [EIP-609](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-609.md).

**Comment by arkpar** [comment]
EIP-649 is implemented in #5855

**Comment by drandreaskrueger** [comment]
Is here the right place to ask about [EIP658](https://github.com/raiden-network/raiden/issues/1067#issuecomment-333641359)? Supposedly needed for raiden.
Thanks.

**Comment by 5chdn** [comment]
@drandreaskrueger EIP-658 is included in #5855 and should be included in master.

**Comment by rphmeier** [comment]
We need to implement the difficulty-adjustment JSON tests (currently residing in BasicTests folder) if we haven't already.

**Comment by 5chdn** [comment]
can we close this btw?

**Comment by 5chdn** [comment]
Assuming done with #6686
