### ISSUE TITLE
WASM MVP

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#6056]
Whats' left

- [x] calls (regular, static, call_code) #6132 
- [x] ~~storage gas metering~~ (managed by regular schedule)
- [x] memory allocations gas metering #6638 
- [x] static memory region gas charge #6638 
- [x] cost table for wasm opcodes #6638

**Comment by NikVolf** [comment]
waiting for #6073 for proper schedule management
