### ISSUE TITLE
Tracking issue util refactor

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6418]
- [ ] @Hawstein journaldb and rocksdb dependencies should be separated from util.
- [ ] @Hawstein all trie traits from util should be separated from util.
- [ ] migrations should be a library
- [x] @debris -> replace sha3::Hashable trait and all of usages of it with a simple function called `hash`
- [x] @debris -> this `hash` function should be a standalone library importing C impl of sha3 and tiny-keccak (for updatable sha3s)
- [x] @folsen util should not reexport bigint
- [x] @Hawstein util should not reexport ansi_term
- [x] @axelchalon -> util should not reexport HeapSizeOf
- [x] @Hawstein util should not reexport ParkingLot
- [x] @debris util should not reexport `vector::*`
- [x] @debris triehash should be separated from util
- [x] @Hawstein semantic_version should be separated from util
- [x] @Hawstein timer::PerfTimer should be a part of ethcore
- [x] @debris error::UtilError should be replaced by error_chain
- [ ] remove public reexports of traits modules
- ~flatten `util` subcrates~ (controversial)

**Comment by rphmeier** [comment]
I'm not convinced about flattening util subcrates. Why not group non-blockchain-specific utilities within a single folder?

**Comment by debris** [comment]
ok, let's keep all subcrates in util directory for now. We'll discuss it again someday

**Comment by debris** [comment]
I'll take

```
- [ ] replace sha3::Hashable trait and all of usages of it with a simple function called `hash`
- [ ] this `hash` function should be a standalone library importing C impl of sha3 and tiny-keccak (for updatable sha3s)
```

**Comment by NikVolf** [comment]
Also fixed hash should be crates.io library dependant on bigint and little more

**Comment by axelchalon** [comment]
I'll take `util should not reexport HeapSizeOf` for now

**Comment by debris** [comment]
I will take `triehash should be separated from util`

**Comment by folsen** [comment]
I'll take `util should not reexport bigint`

**Comment by Hawstein** [comment]
I'll take `util should not reexport ansi_term` if you guys don't mind:)

**Comment by Hawstein** [comment]
I'll take one more: `util should not reexport ParkingLot`.

**Comment by debris** [comment]
@Hawstein thanks, merged!

**Comment by Hawstein** [comment]
I will take `timer::PerfTimer should be a part of ethcore`.

**Comment by Hawstein** [comment]
I will take `semantic_version should be separated from util`.

**Comment by Hawstein** [comment]
I will take 
* journaldb and rocksdb dependencies should be separated from util.
* all trie traits from util should be separated from util.

**Comment by Hawstein** [comment]
@debris Should I move the `journaldb`, `migration` and `trie` out of `util/src` dir and put them in the `util/` dir just like other libs. Seems that this is a reasonable way to arrange them.

**Comment by debris** [comment]
> @debris Should I move the `journaldb`, `migration` and `trie` out of `util/src` dir and put them in the `util/` dir just like other libs. Seems that this is a reasonable way to arrange them.

@Hawstein yes, this would be a great first step. Eventually, we would also like to decouple `journaldb` and `rocksdb` :)

**Comment by rphmeier** [comment]
@debris they are already decoupled to some degree via the `KeyValueDB` trait.

**Comment by debris** [comment]
I will take `error::UtilError should be replaced by error_chain`

**Comment by Hawstein** [comment]
@debris Hi, I am working on the `all trie traits from util should be separated from util`. Since it depends lots of stuffs in `util/src`, so I decide to move all the `*.rs` file in `util/src` out of the src dir and make it a lib. It needs to be done for other tasks too. Does it make sense for you?

**Comment by debris** [comment]
@Hawstein yes, I believe it's one of the last things needed ;)

**Comment by Hawstein** [comment]
@debris Great! Then I will take the following tasks too:
* migrations should be a library
* remove public reexports of traits modules

Since once I make those `*.rs` files into a lib, the above tasks are almost done.
