### ISSUE TITLE
Release next-beta 1.8.0.

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#6688]
**Step 1**: Wind up development:

- [x] check for known bugs (~~feel free to add tickets here~~, **bold are blockers**)
  - [x] [**#4833** metropolis release](https://github.com/paritytech/parity/issues/4833) core **consensus**
  - [ ] ~~[#5968 panicked; qed;](https://github.com/paritytech/parity/issues/5968) core~~
  - [ ] ~~[#6280 sync io / disk usage](https://github.com/paritytech/parity/issues/6280) core~~
  - [ ] ~~[#6326 shutdown corrupts db](https://github.com/paritytech/parity/issues/6326) core~~
  - [ ] ~~[#6372 warp sync not warpy](https://github.com/paritytech/parity/issues/6372) core~~
  - [x] [#6418 util refactor 0](https://github.com/paritytech/parity/issues/6418) core
  - [x] [#6484 warp sync fail](https://github.com/paritytech/parity/issues/6484) core
  - [x] [#6485 graceful exit wrong cli falgs](https://github.com/paritytech/parity/issues/6485) core
  - [x] [**#6534** badge display](https://github.com/paritytech/parity/issues/6534) ui **picops**
  - [x] [**#6549** token balances](https://github.com/paritytech/parity/issues/6549) ui **polkadot**
  - [ ] ~~[#6593 main net sync stuck](https://github.com/paritytech/parity/issues/6593) core~~
  - [ ] ~~[#6637 missing responses eth_get_logs](https://github.com/paritytech/parity/issues/6637) core~~
  - [x] [#6657 warp sync on archive node?](https://github.com/paritytech/parity/issues/6657) core
  - [x] [**#6658** tokens again](https://github.com/paritytech/parity/issues/6658) ui **polkadot**
  - [x] [**#6667** signer not working](https://github.com/paritytech/parity/issues/6667)  public node **picops** **polkadot**
  - [x] [#6669 misleading error](https://github.com/paritytech/parity/issues/6669) ui
  - [ ] ~~[#6693 util refactor 1](https://github.com/paritytech/parity/issues/6693) core~~
  - [x] [**#6700** dapp reg broken](https://github.com/paritytech/parity/issues/6700) dapp ui **polkadot**
- [x] notify devs to submit any remaining PRs
- [x] merge any outstanding PRs
  - [x] [#6664 fix build warnings](https://github.com/paritytech/parity/pull/6664) core
  - [x] [**#6686** potential modexp len overflow](https://github.com/paritytech/parity/pull/6686) core **consensus**
  - [x] [#6687 difficulty tests](https://github.com/paritytech/parity/pull/6687) core
  - [x] [#6690 separate migrations util](https://github.com/paritytech/parity/pull/6690) core
  - [x] [#6691 warp sync archive node](https://github.com/paritytech/parity/pull/6691) core
  - [x] [#6694 prevent going offline while warp sync](https://github.com/paritytech/parity/pull/6694) core
  - [x] [#6701 fix address selector](https://github.com/paritytech/parity/pull/6701) ui
  - [x] [#6702 fix ascii to hex](https://github.com/paritytech/parity/pull/6702) rpcapi
  - [x] [#6705 remove deps rustc_serialize](https://github.com/paritytech/parity/pull/6705) core
  - [x] [#6707 signer signs data](https://github.com/paritytech/parity/pull/6707) ui
  - [x] [#6708 public node signer fix](https://github.com/paritytech/parity/pull/6708) ui
  - [x] [#6710 vouchfor display](https://github.com/paritytech/parity/pull/6710) ui
  - [x] [#6711 graceful exit cli flags](https://github.com/paritytech/parity/pull/6711) core
  - [x] [#6714 fix gas estimation](https://github.com/paritytech/parity/pull/6714) dapps ui
  - [x] [#6718 returndata out of bounds check](https://github.com/paritytech/parity/pull/6718) core **consensus**
  - [x] [#6719 check vouch status](https://github.com/paritytech/parity/pull/6719) ui
  - [x] [#6723 reject invalid cli flags](https://github.com/paritytech/parity/pull/6723) core
  - [x] [#6725 fix tokens and badges](https://github.com/paritytech/parity/pull/6725) ui
  - [x] [#6730 badges again](https://github.com/paritytech/parity/pull/6730) ui
  - [x] [#6741 modexp again](https://github.com/paritytech/parity/pull/6741) core **consensus**

**Step 2**: Conduct QA:

- [ ] ask all core devs for QA sign off
- [ ] check all JSON consensus tests pass with all valid configurations
- [ ] do a full sync
- [ ] deploy netstats node
- [ ] test invocation with each major CLI option

**Step 3**: Conduct release:

- [x] merge `beta` branch to `stable` and bump patch version (THIS_TRACK `stable`)
- [x] merge `master` branch to `beta` and bump patch version (THIS_TRACK `stable`)
- [x] new tag for specific version (i.e. 1.7.0-stable) on HEAD of `stable`.
- [x] new tag for specific version (i.e. 1.8.0-beta) on HEAD of `beta`.
- [x] update all versions in master (Cargo.toml, windows installer, macos installer)
  - [ ] Cargo.toml (version key)
  - [ ] util/Cargo.toml (version key)
  - [ ] nsis/installer.nsi (VERSIONMINOR and VERSIONBUILD keys)
  - [ ] mac/Parity.pkgproj (VERSION key)
  - [ ] cargo update -p ethcore-util
- [x] prepare any binaries that are manual for both beta and stable
  - [ ] homebrew versions and checksums

**Step 4**: Publish release:

- [x] new release in github, add sha256sums
- [x] authorize auto-update on operations proxy contract
- [x] update parity-news (maybe add blog article)
- [ ] set up all binary paths on wiki
- [ ] set up all binary paths on install guides
- [ ] bump website so it's tracking master (i.e. 1.9) progress
- [ ] update README and wiki
- [x] push out to social networks
- [x] close this issue & the 1.8 milestone

**Comment by roninkaizen** [comment]
great overview-
thank you!

**Comment by 5chdn** [comment]
@roninkaizen It's not everything that is in 1.8, just the last-minute open tasks.

**Comment by 5chdn** [comment]
takeaways:

- more clear communication of feature-freeze.
- check if UI is doing what it is supposed to do.
- kovan sync was broken. check all networks.
- auto-updater required patch. check auto-updater.
- one-line installer and homebrew should always point to beta.
- update readme, docker readme, brew readme.
- update api docs (json-rpc).
- in general more QA before release.
