### ISSUE TITLE
Last part of util refactor

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6693]
last part of #6418

- [x] `kvdb` should be separated into 2 separate crates: `kvdb` and `kvrocksdb` which implements key-value interface for rocksdb
- [x] `journal` crate should be separated from util. `overlaydb` and `util_error` crate should be merged into it. also `UtilError` should be just renamed to `Error`.
- [x] `cache` should be separated from `util`
- [ ] `util` should be dissolved

**Comment by debris** [comment]
I will take
- `kvdb` should be separated into 2 separate crates: `kvdb` and `kvrocksdb` which implements key-value interface for rocksdb

**Comment by 0x7CFE** [comment]
I will take `cache` and then probably `journal` stuff.

**Comment by 0x7CFE** [comment]
Now working on `journal`.
