### ISSUE TITLE
Release next-beta 1.9.0

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#7071]
**Step 0**: Tighten Roadmap:

- [x] Decide on rough timeline
  - [x] Feature freeze: Dec 31, 2017
  - [x] Estimaged release: **Jan 22, 2018**
- [x] Decide on important features to be inlcuded
  - [x] User Interface 2.0
  - [x] Bug Fixes, bug fixes, bug fixes, ...

**Step 1**: Wind up development:

- [x] notify devs to submit any remaining PRs
- [x] notify core devs about feature-freeze (Dec-31)
- [x] check for release-blockers (let's make them **bold**)
  - [x] **Initial Sync disk IO / write amplification / disk usage** #6280 
  - [x] **Parity warp sync is no longer very warpy.** #6372 
  - [x] **Update Branding Everywhere** #7294mismatch"'** 
- [x] check for known high-priority bugs and tasks (_feel free to add tickets here_)
  - [x] Stage 1 block verification failed for 5c00…6234: Block(DifficultyOutOfBounds(OutOfBounds { min: None, max: Some(340282366920938463463374607431768211455), found: 340282366920938463463374607431768211456 })) #5689
  - [x] Skipping the account creation wizard fails #6158
  - [x] Cannot run Rust tests on Parity Gitlab in the specific scenario #6507 
  - [x] Last part of util refactor #6693
  - [x] Stage 1 block verification failed #6704
  - [x] UnknownUncleParent while syncing #6761
  - [x] thread '<unknown>' has overflowed its stack #6821
  - [x] Thread 'IO Worker #0' panicked at 'DB flush failed.: "Error converting string"' #6959
  - [x] RPC using high cpu & Upgrade to 1.7.8 failed #6981
  - [x] 100% CPU utilization and RPC service doesn’t response #6983
  - [x] mac binaries for ethabi, ethstore, ethkey #7119
  - [x] Tokens not showing up #7126
  - [x] Parity creating snapshots even if disabled #7133
  - [x] "One liner install" on Linux gives 1.8.2, but latest to download is 1.8.4 #7293
  - [x] Parity stops; Issue: all back-references to answered requests have been filled #7416
  - [x] Parity PoA authorities are not syncing #7441
- [x] check for other known bugs worth fixing (no point in releasing known "bugs")
  - [x] [is:issue is:open label:F2-bug ](https://github.com/paritytech/parity/issues?page=1&q=is%3Aissue+is%3Aopen+label%3AF2-bug)
- [x] merge any outstanding PRs (everything "1.9" and not "on-ice")
  - [x] [is:pr is:open milestone:1.9 -label:A1-onice](https://github.com/paritytech/parity/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20milestone%3A1.9%20-label%3AA1-onice)

**Step 2**: Conduct QA:

- [ ] hire someone for QA
  - [ ] check all JSON consensus tests pass with all valid configurations
  - [ ] test invocation with each major CLI option
  - [x] do a full sync on foundation network
  - [x] check sync on ropsten and kovan
  - [x] check if UI is doing what it is supposed to do.

**Step 3**: Conduct release:

- [x] archive `stable` branch to something like `old-stable-1.7`(THIS_TRACK `oldstable`) 
- [x] merge `beta` branch to `stable` and bump patch version (THIS_TRACK `stable`)
- [x] merge `master` branch to `beta` and bump patch version (THIS_TRACK `beta`)
- [x] new tag for specific version (`1.8.7` and `stable-release`) on HEAD of `stable`.
- [x] new tag for specific version (`1.9.0 and `beta-release`) on HEAD of `beta`.
- [x] update all versions in master to 1.10.0 (Cargo.toml, windows installer, macos installer)
  - [x] Cargo.toml (version key)
  - [x] util/version/Cargo.toml (version key)
  - [x] nsis/installer.nsi (VERSIONMINOR and VERSIONBUILD keys)
  - [x] mac/Parity.pkgproj (VERSION key)
  - [x] mac/Parity/Info.plist (CFBundleShortVersionString)
  - [x] cargo update -p parity-version
- [x] prepare any binaries that are manual for both beta and stable
- [ ] update public nodes (wallet.parity.io, kovan-wallet.parity.io)

**Step 4**: Publish release:

- [x] new release in github, add sha256sums
- [x] update homebrew versions and checksums
- [ ] update one-line installer
- [x] flush Cloudflare caches
- [x] verify that vanity-service returns proper versions (for [stable](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=stable) and [beta](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=beta-release) channels)
- [ ] authorize auto-update on operations proxy contract
- [ ] update parity-news (and write a blog article)
- [x] update README, docker README, brew README
- [ ] update Wiki and JSON-RPC API docs
- [x] push out to social networks
- [x] close this issue & the 1.9 mileston

**Comment by debris** [comment]
and let's schedule the next release for Jan 8th (7 weeks, because of Christmas)

**Comment by 5chdn** [comment]
And feature freeze Dec 22nd?

**Comment by debris** [comment]
y

**Comment by 5chdn** [comment]
We need to finalize the rebranding in 1.9

**Comment by 5chdn** [comment]
Remove expanse #7146
