### ISSUE TITLE
Tracking issue of wasm support in Kovan

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#7292]
- [ ] merge https://github.com/paritytech/parity/pull/7970
- [x] augment call to include gas limit #7356
- [x] refactor runtime to avoid allocation in contract memory
- [x] drop allocations from runtime 
- [x] audit functionality to reduce risk of further hardforks
- [x] ban floats
- [x] test the hardfork
- [x] deterministic stack limiter
- [x] decide block number 6,500,000

**Comment by 5chdn** [comment]
ref #7080
