### ISSUE TITLE
Release next-beta 1.10

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#7699]
**Step 0**: Tighten Roadmap:

- [x] Decide on rough timeline
  - [x] Feature freeze: Feb 23, 2018
  - [x] Estimated release: **Mar 05, 2018**
- [x] Decide on important features to be inlcuded
  - [x] Remove UI
  - [ ] State Change Objects
  - [ ] Parity DB
  - [ ] Casper FFG Testnet
  - [ ] Light Client
  - [ ] Light Wallet
  - [ ] Bug Fixes, bug fixes, bug fixes, ...

**Step 1**: Wind up development:

- [x] notify core devs about feature-freeze (Feb-23)
- [x] notify devs to submit any remaining PRs
- [x] reality-check against the [roadmap-known-issues](https://paritytech.github.io/wiki/Known-Issues-Priorities)
- [x] merge any outstanding PRs (everything "1.10" and not "on-ice": [is:pr is:open milestone:1.10 -label:A1-onice](https://github.com/paritytech/parity/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20milestone%3A1.10%20-label%3AA1-onice))

**Step 2**: Conduct QA:

- [ ] hire someone for QA
  - [ ] check all JSON consensus tests pass with all valid configurations
  - [ ] test invocation with each major CLI option
  - [ ] do a full sync on foundation network
  - [ ] check sync on ropsten and kovan
  - [ ] check if UI is doing what it is supposed to do.

**Step 3**: Conduct release:

- [x] archive `stable` branch to something like `old-stable-1.8`(THIS_TRACK `oldstable`) 
- [x] merge `beta` branch to `stable` and bump patch version (THIS_TRACK `stable`)
- [x] merge `master` branch to `beta` and bump patch version (THIS_TRACK `beta`)
- [x] new tag for specific version (`1.9.x` and `stable-release`) on HEAD of `stable`.
- [x] new tag for specific version (`1.10.0` and `beta-release`) on HEAD of `beta`.
- [x] update all versions in master to `1.11.0` (Cargo.toml, windows installer, macos installer)
  - [x] Cargo.toml (`version` key)
  - [x] util/version/Cargo.toml (`version` key)
  - [x] nsis/installer.nsi (`VERSIONMINOR` and `VERSIONBUILD` keys)
  - [x] mac/Parity.pkgproj (`VERSION` key)
  - [x] mac/Parity/Info.plist (`CFBundleShortVersionString`)
  - [x] `cargo update -p parity-version`
- [x] prepare any binaries that are manual for both beta and stable
- [ ] update public nodes (wallet.parity.io, kovan-wallet.parity.io)

**Step 4**: Publish release:

- [x] new release in github, add sha256sums
- [x] update homebrew versions and checksums
- [x] update one-line installer
- [ ] flush Cloudflare caches
- [x] verify that vanity-service returns proper versions (for [stable](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=stable) and [beta](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=beta-release) channels)
- [ ] authorize auto-update on operations proxy contract
- [ ] update parity-news (and write a blog article)
- [ ] update README, docker README, brew README
- [ ] update Wiki and JSON-RPC API docs
- [ ] push out to social networks
- [x] close this issue & the 1.10 mileston
