### ISSUE TITLE
rlp module refactor

### ISSUE THREAD

**Issue by debris** [paritytech/parity#8033]
should fix issues like #8031 or #8032

- `rlp::decode` should return `Result<_, DecoderError>`
- get rid of `Rlp`
- `UntrustedRlp` should be renamed to `Rlp`

**Comment by debris** [comment]
issues is marked as `easy` and `epic`, cause it's easy, but time consuming

**Comment by ascjones** [comment]
I'm looking at this

**Comment by ascjones** [comment]
This is being split across several PRs, since lots of changes

Phases:

- [ ] Replace 'trusted' usages of Rlp with UntrustedRlp and handle Results, unsafely unwrapping where appropriate
- [ ] Replace usages of Rlp where data received from other nodes, and propogate Results
- [ ] Delete original Rlp and rename UntrustedRlp to Rlp

**Comment by ascjones** [comment]
Just the last bit needs doing now, changing decode to return `Result<_, DecoderError>`. I'll leave that here for now, I've unassigned myself for now so anyone else can pick it up or I'll come back to it later.

**Comment by dvdplm** [comment]
I'll have a stab at the `decode` changes. :)

**Comment by ascjones** [comment]
All done!
