### ISSUE TITLE
Release next-beta 1.11

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#8190]
**Prepare Code:**
- [x] Decide on a rough timeline, feature freeze, release date
  - [x] Feature freeze: Apr 20, 2018
  - [x] Estimated release: **Apr 30, 2018**
- [x] Do a reality-check against the [roadmap-known-issues](https://paritytech.github.io/wiki/Known-Issues-Priorities)
- [x] **Make sure UI related changes are done**
  - [ ] Remove UI and Public Node completely
  - [x] Replace :8180 with static page (link to docs, simple stats)
  - [ ] Remove (rework?) installers (code, ci, ...) and promote separate UI
- [x] Notify devs about a new beta release, ask to submit PRs
- [x] Create backports for all PRs tagged with **B0-patch**
- [x] Merge all pending pull requests that should be included in the next beta

**Freeze Code:**
- [x] archive `stable` branch to something like `old-stable-1.9`
  - [x] change THIS_TRACK in code to `oldstable`
  - [x] protect that branch in Github settings
- [x] merge `beta` branch to `stable`
  - [x] and bump track (THIS_TRACK `stable`)
  - [x] check ci scripts for `stable` or `*1.9*` specifics -> `*1.10*`
  - [x] check the js/ui scripts from track specific stuff
- [x] merge `master` branch to `beta`
  - [x] and bump track (THIS_TRACK `beta`)
  - [x] check ci scripts for `beta` or `*1.10*` specifics -> `*1.11*`
  - [x] check the js/ui scripts from track specific stuff
- [x] On master: bump minor and patch version in code to 1.12.0
  - [x] Cargo.toml (`version` key)
  - [x] util/version/Cargo.toml (`version` key)
  - [x] nsis/installer.nsi (`VERSIONMINOR` and `VERSIONBUILD` keys)
  - [x] mac/Parity.pkgproj (`VERSION` key)
  - [x] mac/Parity/Info.plist (`CFBundleShortVersionString`)
  - [x] `cargo update -p parity-version`
- [x] Run `cargo update -p parity-version` on the new branches
- [x] On stable: bump and consider a stable release

**Conduct QA:**
- [x] Check if Gitlab pipeline on beta and latest HEAD is green
- [x] Create a test tag for testing the full release pipeline, e.g., `v1.11.0-rc0`
- [x] Fix all issues with the test tag until CI is all green
- [x] Create a release tag, e.g., `v1.11.0` on HEAD of beta, wait for binaries
- [x] Publish binaries for the tag only
- [x] Notify devs about available binaries for testing: https://vanity-service.parity.io/parity-binaries?format=markdown&version=v1.11.0
  - [ ] check all JSON consensus tests pass with all valid configurations
  - [ ] test invocation with each major CLI option
  - [ ] do a full sync on foundation network
  - [ ] check sync on ropsten and kovan
  - [ ] check if UI is doing what it is supposed to do

**Publish Release**:
- [x] Publish binaries and link beta-release for vanity service and docker (and/or stable-release)
- [x] ~~update~~ shut down the public nodes (wallet.parity.io, kovan-wallet.parity.io)
- [x] draft a new release in github, add sha256sums
- [x] update homebrew versions and checksums
- [x] release snapcraft beta (or stable), see CI for snap build ID
- [x] update one-line installer (should work automatically by now)
- [x] flush Cloudflare caches
- [x] verify that vanity-service returns proper versions (for [stable](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=stable-release) and [beta](https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&version=beta-release) channels)
- [ ] check & update download links at www.parity.io
- [ ] authorize auto-update on operations proxy contract
- [ ] update parity-news (and write a blog article)
- [x] update README, docker README, brew README
- [ ] update Wiki and JSON-RPC API docs
- [ ] push out to social networks
- [ ] close the meta issue & the 1.11 milestone

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity/releases/tag/v1.11.0

**Comment by 5chdn** [comment]
**Backports for 1.10.4-stable**
- [ ] #8486 `Remove depth == 0 check for tracing precompiled contracts`
- [ ] #8545 `Handle socket address parsing errors`
- [ ] #8570 `Decoding headers can fail`
- [ ] #8596 `Fix account list double 0x display`

**Backports for 1.11.1-beta**
- [ ] #8486 `Remove depth == 0 check for tracing precompiled contracts`
- [ ] #8530 `Don't block sync when importing old blocks`
- [ ] #8543 `Refactoring ethcore-sync - Fixing warp-sync barrier`
- [ ] #8545 `Handle socket address parsing errors`
- [ ] #8555 `Fix packet count when talking with PAR2 peers`
- [ ] #8570 `Decoding headers can fail`
- [ ] #8578 `Add whisper CLI to the pipelines`
- [ ] #8579 `Rename whisper-cli binary to whisper`
- [ ] #8595 `Whisper-cli remove manually added text to the errors`
- [ ] #8596 `Fix account list double 0x display`

**Up next**

- [ ] #8528 `Fix light sync on side chains`
- [ ] #8611 `Gitlab test script fixes`
- [ ] #8573 `Fix BlockReward contract "arithmetic operation overflow" `

**Comment by 5chdn** [comment]
**Backports for 1.10.5-stable**
- [ ] #8528 Fix light sync with initial validator-set contract
- [ ] #8641 Don't open Browser post-install on Mac, fixes #8194
- [ ] #8682 Fix cli signer
- [ ] #8683 Set the request index to that of the current request
- [ ] #8686 network-devp2p: handle UselessPeer disconnect
- [ ] #8710 ethcore-sync: fix connection to peers behind chain fork block

**Backports for 1.11.2-beta**
- [ ] #8528 Fix light sync with initial validator-set contract
- [ ] #8544 Resumable warp-sync / Seed downloaded snapshots
- [ ] #8641 Don't open Browser post-install on Mac, fixes #8194
- [ ] #8642 Fix ancient blocks not downloading
- [ ] #8656 Fix PoW blockchains sealing notifications in chain_new_blocks
- [ ] #8658 Shutdown the Snapshot Service early
- [ ] #8682 Fix cli signer
- [ ] #8683 Set the request index to that of the current request
- [ ] #8686 network-devp2p: handle UselessPeer disconnect
- [ ] #8691 Fix local transactions policy.
- [ ] #8710 ethcore-sync: fix connection to peers behind chain fork block
- [ ] #8744 Custom Error Messages on ENFILE and EMFILE IO Errors
- [ ] #8745 CI: Fixes for Android Pipeline

**Up next**
- [ ] .

**Comment by 5chdn** [comment]
**Backports for 1.10.7-stable**
- [ ] #8803 Fixed AuthorityRound deadlock on shutdown
- [x] #8821 Specify critical release flag per network (via #8855)
- [ ] #8822 CI: Fix docker tags
- [ ] #8854 Fix concurrent access to signer queue
- [ ] #8876 update jsonrpc libs, fixed ipc leak
- [ ] #8886 Add new ovh bootnodes and fix port for foundation bootnode 3.2
- [ ] #8891 Block 0 is valid in queries
- [ ] #8892 Add ETC Cooperative-run load balanced parity-based bootnode
- [ ] #8906 Minor fix in chain supplier and light provider

**Backports for 1.11.4-beta**
- [ ] #8790 devp2p: Move UDP socket handling from Discovery to Host.
- [ ] #8796 Handle removed logs in filter changes and add geth compatibility field
- [ ] #8803 Fixed AuthorityRound deadlock on shutdown
- [x] #8821 Specify critical release flag per network (via #8856)
- [ ] #8822 CI: Fix docker tags
- [ ] #8832 ethcore: fix ancient block import error handling
- [ ] #8834 Disable parallel verification and skip verifiying already imported txs.
- [ ] #8854 Fix concurrent access to signer queue
- [ ] #8867 Don't allocate in expect_valid_rlp unless necessary
- [ ] #8876 update jsonrpc libs, fixed ipc leak
- [ ] #8886 Add new ovh bootnodes and fix port for foundation bootnode 3.2
- [ ] #8891 Block 0 is valid in queries
- [ ] #8892 Add ETC Cooperative-run load balanced parity-based bootnode
- [ ] #8906 Minor fix in chain supplier and light provider

**Up next**
- [ ] #8882 Allow disabling local-by-default for transactions with new config entry
