### ISSUE TITLE
Parity node clean-up tracker ticket.

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#8649]
The next release shall not happen if we did not address the following points.

---
- [x] Remove MacOS installers, trays, etc. from code (and CI) #8875
- [x] Remove Windows installers, trays, etc. from code (and CI) #8778

---
- [x] Remove all left-overs of User Interface from code, CLI, etc. #8783
- [x] Remove all left-overs of Public Node from code, CLI, etc. #8758 (#8763)

---
- [ ] ~~Enforce consistency of crate naming, rename `ethcore-*` crates to `parity-*`~~

**Comment by folsen** [comment]
I would argue the last point is not a release blocker. That is strictly behind-the-scenes and could actually be a lot of work.

**Comment by tomusdrw** [comment]
Yeah, I had also a discussion with @debris where we think that `parity-*` should be reserved for potential secondary product names (like `parity-evm`, etc) and not necessarily internal crates. Most of the crates are sort of "ethereum core" and that's where the name came from (suprisingly colliding later with the company name).

**Comment by debris** [comment]
Crate renaming definitely shouldn't be a release blocker. I would also reorganize location of our executables. Now they are difficult to find for people not familiar with the project. It would be cool if we place all of them in a single directory

**Comment by 5chdn** [comment]
Makes sense, thanks for your input.

**Comment by sorpaas** [comment]
I'm going to take a look at UI and Public Node removal if no one else is working on that.
